### ISSUE TITLE
MemoryCache disposed exception

### ISSUE THREAD

**Issue by laozhuorun** [aspnetboilerplate/module-zero-forsaken#390] opened 2017-06-22 10:14 UTC
use module-zero in .net core 1.1

here is exception detail：

ERROR 2017-06-22 14:27:33,118 [4    ] Mvc.ExceptionHandling.AbpExceptionFilter - Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
   at Microsoft.Extensions.Caching.Memory.MemoryCache.CheckDisposed()
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at Abp.Runtime.Caching.Memory.AbpMemoryCache.GetOrDefault(String key)
   at Abp.Runtime.Caching.CacheBase.Get(String key, Func`2 factory)
   at Abp.Runtime.Caching.CacheExtensions.Get[TKey,TValue](ICache cache, TKey key, Func`2 factory)
   at Castle.Proxies.Invocations.ITenantCache_GetOrNull.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.TenantCache`2Proxy.GetOrNull(Int32 tenantId)
   at Abp.MultiTenancy.TenantStore.Find(Int32 tenantId)
   at Abp.MultiTenancy.TenantResolver.GetTenantIdFromContributors()
   at Abp.MultiTenancy.TenantResolver.ResolveTenantId()
   at Abp.Runtime.Session.ClaimsAbpSession.get_TenantId()
   at Abp.Auditing.AuditingHelper.CreateAuditInfo(MethodInfo method, IDictionary`2 arguments)
   at Abp.AspNetCore.Mvc.Auditing.AbpAuditActionFilter.<OnActionExecutionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()

**Comment by laozhuorun** [comment] 2017-06-22 10:32
DEBUG 2017-06-22 14:27:33,124 [4    ] ore.Mvc.Internal.ControllerActionInvoker - Request was short circuited at exception filter 'Abp.AspNetCore.Mvc.ExceptionHandling.AbpExceptionFilter'.
DEBUG 2017-06-22 14:27:33,124 [4    ] etCore.Mvc.Internal.ObjectResultExecutor - No information found on request to perform content negotiation.
DEBUG 2017-06-22 14:27:33,124 [4    ] etCore.Mvc.Internal.ObjectResultExecutor - Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response.
INFO  2017-06-22 14:27:33,124 [4    ] etCore.Mvc.Internal.ObjectResultExecutor - Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
INFO  2017-06-22 14:27:33,124 [4    ] ore.Mvc.Internal.ControllerActionInvoker - Executed action Abp.AspNetCore.Mvc.Controllers.AbpUserConfigurationController.GetAll (Abp.AspNetCore) in 9.8788ms
DEBUG 2017-06-22 14:27:33,124 [4    ] Microsoft.AspNetCore.Server.Kestrel      - Connection id "0HL5P6DUK58HQ" completed keep alive response.
INFO  2017-06-22 14:27:33,125 [4    ] soft.AspNetCore.Hosting.Internal.WebHost - Request finished in 19.4502ms 500 application/json; charset=utf-8

**Comment by laozhuorun** [comment] 2017-06-22 10:34
when access api ：AbpUserConfigurationController/GetAll，and cookies exist item “Abp.TenantId” value  is 1

**Comment by hikalkan** [comment] 2017-06-22 19:11
Is that always happening or just one time?

**Comment by laozhuorun** [comment] 2017-06-23 02:35
always happening on Application run  for a while

**Comment by hikalkan** [comment] 2017-06-23 02:38
Did you make any change? For instance, have you upgraded Abp package version? If so, what was old version and current version?

**Comment by laozhuorun** [comment] 2017-06-23 02:39
the version i use is 2.0.2

**Comment by hikalkan** [comment] 2017-07-15 20:28
Have you solved this issue? Can you repeat it with a fresh new startup template?

**Comment by KaterynaZorina** [comment] 2018-03-08 09:18
Hi! I faced similar problem with AbpMemoryCache disposing. Do you have any solutions for this problem?

**Comment by ismcagdas** [comment] 2018-03-08 10:08
@KaterynaZorina actually we couldn't reproduce this problem. Do you know a way to reproduce it ?

**Comment by KaterynaZorina** [comment] 2018-03-08 11:17
@ismcagdas unfortunately I can't tell you how to reproduce this problem. It appears randomly. Here is stack trace:

ERROR 2018-03-08 10:53:08,381 [64   ] bp.Runtime.Caching.Memory.AbpMemoryCache - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
   at Microsoft.Extensions.Caching.Memory.MemoryCache.CheckDisposed()
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at Abp.Runtime.Caching.Memory.AbpMemoryCache.GetOrDefault(String key)
   at Abp.Runtime.Caching.CacheBase.GetOrDefaultAsync(String key)
   at Abp.Runtime.Caching.CacheBase.<GetAsync>d__19.MoveNext()
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
   at Microsoft.Extensions.Caching.Memory.MemoryCache.CheckDisposed()
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at Abp.Runtime.Caching.Memory.AbpMemoryCache.GetOrDefault(String key)
   at Abp.Runtime.Caching.CacheBase.GetOrDefaultAsync(String key)
   at Abp.Runtime.Caching.CacheBase.<GetAsync>d__19.MoveNext()

**Comment by ismcagdas** [comment] 2018-03-08 11:25
@KaterynaZorina does it happen when you are working on the app UI ? If so, what was the last operation caused this problem ? A few users had a similar problem when deleting a user on the UI.

**Comment by KaterynaZorina** [comment] 2018-03-08 12:06
@ismcagdas I didn't delete users. This issue appears randomly after different API calls. But I can't reproduce it. Clearing cache solves this issue for awhile.

**Comment by ismcagdas** [comment] 2018-03-09 07:01
Probably this problem will be solved with https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2846. We will release ABP v3.5 in a short time. I'm closing this issue, please reopen if https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2846 doesn't fix the problem.

**Closed by ismcagdas** 2018-03-09 07:01 UTC
Labels: problem
